### ISSUE TITLE
El programa se cierra

### ISSUE THREAD

**Issue by michaelonepiece21** [7ouma/CrunchySubs#8]
Luego de pegar el link de Crunchyroll y de seleccionar el idioma, se cierra el programa y no se descargó el subtítulo. ¿Hay algun problema con el cfscrape o es el mismo programa en sí?

**Comment by THeXES** [comment]
Me ocurre lo mismo.

**Comment by rs3mk** [comment]
parece que cambiaron algo en el proceso de desencriptado, he probado el script base y da un problema con esta parte b64decode

`    def decode(mediaid, iv, data):
        # Do some black magic
        eq = (mediaid ^ 88140282) ^ (mediaid ^ 88140282) >> 3 ^ int(88140282 ^ mediaid) * 32
        # Creates a 160-bit SHA1 hash padded to 256-bit using zeroes
        key = sha1('$&).6CXzPHw=2N_+isZK' + str(eq)).digest()+'\x00'*12
        iv = b64decode(iv)
        data = b64decode(data)
        cipher = AES.new(key, AES.MODE_CBC, iv)
        decrypteddata = cipher.decrypt(data)
        subfile.close()
        return decompress(decrypteddata)`

también intenté con este otro script y no funciona
https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/blob/master/crunchy-xml-decoder/crunchyDec.py

algo me fije, al dar f5 aquí (de donde se extrae los datos de subs codificados)
crunchyroll.com/xml/?req=RpcApiSubtitle_GetXml&subtitle_script_id=57050

siempre te cambia los valores, no recuerdo si antes era igual.

finalmente con youtube-dl aún se puede extraer los subs.

**Comment by firecrauter** [comment]
> parece que cambiaron algo en el proceso de desencriptado, he probado el script base y da un problema con esta parte b64decode
> 
> ` def decode(mediaid, iv, data): # Do some black magic eq = (mediaid ^ 88140282) ^ (mediaid ^ 88140282) >> 3 ^ int(88140282 ^ mediaid) * 32 # Creates a 160-bit SHA1 hash padded to 256-bit using zeroes key = sha1('$&).6CXzPHw=2N_+isZK' + str(eq)).digest()+'\x00'*12 iv = b64decode(iv) data = b64decode(data) cipher = AES.new(key, AES.MODE_CBC, iv) decrypteddata = cipher.decrypt(data) subfile.close() return decompress(decrypteddata)`
> 
> también intenté con este otro script y no funciona
> https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/blob/master/crunchy-xml-decoder/crunchyDec.py
> 
> algo me fije, al dar f5 aquí (de donde se extrae los datos de subs codificados)
> crunchyroll.com/xml/?req=RpcApiSubtitle_GetXml&subtitle_script_id=57050
> 
> siempre te cambia los valores, no recuerdo si antes era igual.
> 
> finalmente con youtube-dl aún se puede extraer los subs.

Como se hace con youtube-dl?, me pasarías algún tutorial que lo explique u.u. 
Gracias

**Comment by rs3mk** [comment]
`youtube-dl --skip-download --all-subs --sub-format "ass" -u xxxxxxx -p xxxxxxx  "link your anime pag or eps"`

la parte de usuario y password es opcional (-u -p), es obligatorio en series que solo se pueden ver siendo usuario de pago.

**Comment by Solus32** [comment]
Hola @7ouma antes que nada espero que estés bien de salud al igual que tus familiares, por lo de la pandemia. 
Fíjate que me sucede algo igual que a ellos, al momento de pegar la dirección url del subtitulo tarda mucho en darte la opción de que idioma quieres, y ya cuando lo seleccionas te manda error, tengo la última versión de pip, setuptools y cfscrape. Sucede el error en todas los animes viejos o nuevos en ambas páginas de CrunchySubs en Ingles y Español. Tengo la versión CrunchySubs v1.4.2 beta

Este es el error como se muestra

Opciones:
1.- Descargar.
2.- Descargar paquete de enlaces.
3.- Login.
4.- Configuración.
5.- Acerca de..
0.- Salir.
>1
Introduce el enlace: https://www.crunchyroll.com/es/black-clover/episode-129-the-devil-megicula-794724
Lenguajes disponibles:
1) English (US).
2) Español (América Latina).
3) Español (España).
4) Français (France).
5) Português (Brasil).
6) العربية.
7) Italiano.
8) Deutsch.
9) Русский.
10) Todos los lenguajes.
0) Cancelar
> 2
Descargando: Black Clover - 129 [Español (América Latina)].ass
Traceback (most recent call last):
  File "CrunchySubs.py", line 562, in <module>
    subs.saveSubs(subs.downloadSubs(sublist[1][int(seleccion)-1]), titulo)
  File "CrunchySubs.py", line 363, in downloadSubs
    formattedSubs = self.returnSubs(xmlSubs)
  File "CrunchySubs.py", line 182, in returnSubs
    decryptedSubs = self.decodeSubtitles(_id, _iv, _data)
  File "CrunchySubs.py", line 256, in decodeSubtitles
    return zlib.decompress(decryptedData)
zlib.error: Error -3 while decompressing data: incorrect header check

##############################################################
### Y este es la version de pip, setuptools, cfscrape que tengo instaladas ###
##############################################################
Así lo muestra Terminal en Debian Buster

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (44.1.0)
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (20.0.2)
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: cfscrape in /usr/local/lib/python2.7/dist-packages (2.1.1)
Requirement already satisfied, skipping upgrade: requests>=2.6.1 in /usr/local/lib/python2.7/dist-packages (from cfscrape) (2.23.0)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.6.1->cfscrape) (1.25.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.6.1->cfscrape) (2020.4.5.1)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/lib/python2.7/dist-packages (from requests>=2.6.1->cfscrape) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.6.1->cfscrape) (2.9)

Saludos y gracias

**Comment by Solus32** [comment]
Este es el nuevo mensaje de error que sale

1.- Descargar.
2.- Descargar paquete de enlaces.
3.- Login.
4.- Configuración.
5.- Acerca de..
0.- Salir.
>1
Introduce el enlace: https://www.crunchyroll.com/es/one-piece/episode-930-a-lead-performer-queen-the-plague-emerges-794473
Traceback (most recent call last):
  File "CrunchySubs.py", line 489, in (module)
    url = subs.UrlCheck(str(raw_input("Introduce el enlace: ")))
  File "CrunchySubs.py", line 440, in UrlCheck
    self.titulo = soup.find(u"series_title").text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by Vencal** [comment]
Alguien ha encontrado alguna solución?

**Comment by ghost** [comment]
Encontré un archivo codificado de noviembre 2019 y lo probé con el script. Se decodifico sin problemas.
![transform](https://user-images.githubusercontent.com/26800869/91482841-b3e1ee00-e874-11ea-83f0-95e2c3939d7e.jpg)

Luego obtuve un nuevo archivo codificado, pero usando el mismo ID de subtitulo y me arrojo el problema de zlib.
![version2020](https://user-images.githubusercontent.com/26800869/91482990-f73c5c80-e874-11ea-9134-84f22c673e88.png)

puedo asumir que el problema no es la biblioteca ni del script, sino que cambiaron el contenido desde el lado del servidor.
